### ISSUE TITLE
Struct definitions require commas

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#100]
Lots of things in Sidef accept whitespace instead of `,`, like `(1 2)` is the same as (1, 2) which is really useful. 

It's understandable why `struct { a b c }` doesn't work, because a human can't even tell whether `a` or `b` are supposed to be typenames, and `b` or `c` are the field names? 

But it seems like newlines can be unambiguous delimiters for struct fields.

```ruby
  struct Finalized {
    Bool success
    String f7r_name

    Array obj_args
  }
```

**Comment by trizen** [comment]
Good suggestion. Newlines are now allowed to be used as delimiters. Thanks.
