### ISSUE TITLE
Indexable String?

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#36]
It's kind of weird that Sidef strings can't be indexed like `"abc"[0]` I think, I guess I'm just not used to it coming from Python, but most other languages have this property too. 

Or is it preferred / intended to always say `str.chars` or `str.split("")` instead of trying to use String as Array?

**Comment by trizen** [comment]
This feature was actually available in the language in some versions <=0.11, but somehow never made it back into the newer versions (I will re-add it back very soon).

I agree with you, it's a very convenient thing to have into a language, although it's a bit hard to make it efficient without making everything else slow.

Currently, the main method used for string-indexing, is the `.char(i)` method, which is very efficient:

```ruby
var str = "foobar"
say str.char(0)    # f
say str.char(-1)   # r
```
