### ISSUE TITLE
Inner classes get their parent's variables but none of the methods

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#40]
```ruby
#! sidef -WkP12

class ArgParse () {

  class Option (long) {}

  has Hash prog_args = Hash()
  has Hash prog_info = Hash()

  method option (long_name) {
    var a = Option(1)
    a.option # -> Undefined method
    self.prog_args.append(long_name, Option(long_name))
    self.prog_args
  }

}

say ArgParse().option("f")
```

the output (in 3.50) is 

```ruby
Hash("f" => Option(long: "f", prog_args: Hash(), prog_info: Hash()))
```
The `Option` value in the hash has members `prog_args` and `prog_info` which are not defined in Option, but in its outer class. `Option`'s version of the members do not have the same values as `ArgParse`'s version, which implies they're not pointers but they are just copied members.

This would make sense to me if `Option` also inherited the methods from its outer "super"class, but it doesn't seem to.

Is this intentional, or a bug? Is it to discourage me from using nested classes except to subclass data?

**Comment by trizen** [comment]
Classes are allowed to be nested, but inheritance but be explicitly defined, using the syntax: 

```ruby
class Example(...) < SuperClass { 
   ... 
}
```


In the example you provided, you can try something like this:

```ruby
class ArgParse () {

  class Option (long) < ArgParse {
        method bar {
            "in class Option: #{self.long}"
        }
  }

  has Hash prog_args = Hash()
  has Hash prog_info = Hash()

  method option (long_name) {
    self.prog_args.append(long_name, Option(long_name))
    self.prog_args
  }

  method foo  {
    "in class ArgParse: #{self.long}"
  }
}

var opt   = ArgParse().option("f")
var opt_f = opt{:f}

say opt_f.foo       #=> in class ArgParse: f
say opt_f.bar       #=> in class Option: f
```

Please let me know if this answers your question. Thanks!

**Comment by catb0t** [comment]
Ok, it makes a lot of sense, but I still wonder why `class Option {}` gets its enclosing class's data members without any inheritance?

**Comment by trizen** [comment]
> class Option {} gets its enclosing class's data members without any inheritance

Hmm... I wasn't aware of that. I think it's a bug. I will have to look into it.

To document the case, this code should not work:
```ruby
class ArgParse () {

  class Option (long) {
    method foo {
        "data from ArgParse: #{self.bar}"
    }
  }

  has bar = 42

  method option(name) {
      Option(name)
  }
}

var opt = ArgParse().option(:f)

say opt.foo     #=> data from ArgParse: 42
say opt.bar     #=> 42
```

Thanks for reporting this issue!
