### ISSUE TITLE
Hash literal indexing doesn't work inside class methods

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#41]
```ruby
>> class A { has Hash pi = Hash() ; method e { say self.pi{:name} } }           
=> Sidef::Runtime23::main::A
>> var a = A()                                                                  
=> Sidef::Runtime24::main::A=HASH(0x561f3d7957b0)
>> a.pi.append("name", "cat")                                                   
=> Hash("name" => "cat")
>> a.e                                                                          
Hash("name" => "cat")
=> true

>> var hash = Hash()                                                            
=> Hash()
>> hash{:name} = "cat"                                                          
=> cat
>> hash{:name}                                                                  
=> cat
```

(3.50) if you have a method in a class that returns `self.member{:key}` where `member` is a Hash, the string-indexing operation doesn't work and the entire hash is returned instead. 

Actually it doesn't matter if you assign the hash to a local first (`var p = self.pi; return p{:name}`) or use the `return` keyword, this `{"key"}` / `{:key}` syntax is a no-op inside class methods. 

Of course, thankfully you can still get the item by `hash.item("key")` or `hash.fetch("key")` but this is definitely wrong.

**Comment by trizen** [comment]
This is indeed an ambiguity, as we already have the syntax:

```ruby
obj.method{ ... }
```

where `{...}` is a block of code that is passed as an argument to `method`, which conflicts with the syntax for a hash-lookup, therefore, in order to do a hash-lookup, we must say:

```ruby
obj.method(){key}
```

or:

```ruby
obj.method\{key}
```

which is better illustrated with a concrete example:

```ruby
class Example {
    has member = Hash(foo => 42)
}

var obj = Example()

say obj.member\{:foo}       #=> 42
say obj.member(){:foo}      #=> 42
```

**Comment by catb0t** [comment]
I knew that `obj.x{ }` is ambiguous whether it's a function-or-method, but I had never used `obj.x{ }` outside of a method so I didn't realise it wasn't just a `self` thing. 

The fact you can use `()` on a non-callable to disambiguate it from a block is really interesting, and same for the `\` escape I didn't know about. Always more to learn in this language, thank you!
