### ISSUE TITLE
Sequence Typenames can't be ~~ smart-matched

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#42]
Sorry if this is nitpicky, but some builtin Type typenames (the iterable ones) can't be smart-matched against directly because they throw the error
```ruby
Pair ~~ Pair # -> true
Pair().class ~~ Pair.class # -> true 
Pair.class ~~ "a" # -> false 

Pair ~~ "a" # error
"a" ~~ Pair # error 
1 ~~ Pair  # error 
Can't use string ("Sidef::Types::Array::Pair") as an ARRAY ref while "strict refs" in use at /home/cat/perl5/lib/perl5/Sidef/Types/Array/Array.pm line 2358.
```

Array, Pair, Matrix, Bag, Hash, Regex and  Set all do this; `Null` does not, which implies that it's not a *missing method* but just a weird regression.  `Array.pm line 2358` is `Array.contains` and the error line  for `Hash` / `Set` is `500`, inside `Hash.exists`.

It works fine if you call a method on the typename or have an object of that type, like `Array.class` or `1~~[1, 2] == true`.

I know I should use the `.class` or `.ref` method to test the type, but I think the error message is wrong or confusing, those expressions should just be false.

**Comment by trizen** [comment]
Not nitpicking at all. Any reported issue is valuable. Thanks for reporting. :)
