### ISSUE TITLE
Obfuscated example in "Mastering Sidef" 

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#44]
```ruby
(:«2 A 4 H 1 J 3 S»...)[1..4]map{static(ß)=+<tsu rehton fedi
rekca>,.+(ß<<1pop.reverse+(?ß.len ?32.chr :%\,\))}.'join'say
```

It must have worked at one point in August 2015, like pre-0.08 (but I didn't go back any further), v0.08 doesn't mind syntax `[1..4]map` or `<<1pop.reverse` or `?ß.len` , but it dies when calling reverse on the nil `1pop`.

But what did it once do, and how would it be written in modern Sidef? (so that the Wiki doesn't have broken code)

**Comment by trizen** [comment]
Yeah, that is a very old section.

In modern Sidef, the code can be rewritten something like this:

```ruby
[(:«2 A 4 H 1 J 3 S»...){@|1..4}].map{static(ß)=<tsu rehton fedi
rekca>;(_+(ß>>1)[0].reverse+(ß.len ? 32.chr : %\,\))}.'join'.say
```

**Comment by catb0t** [comment]
Cool! You don't think it's worth keeping at the top of the page?
