### ISSUE TITLE
run the tests in scripts/Tests?

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#45]
`make test` runs the install-time tests in `./t`, but doesn't seem to run the Sidef scripts in `scripts/Tests`

`RELEASE_TESTING=1 make test` runs `manifest.t` but that doesn't actually run any of the `.sf` tests either.

`find scripts/Tests/ -name '*.sf'  -exec bin/sidef {} \;` works fine, but I was wondering if i missed a canonical way.

**Comment by trizen** [comment]
For running the tests in the `scripts/Tests` directory, we can use the `-t` special switch:

```
$ sidef -t scripts/Tests/*.sf
```

**Comment by catb0t** [comment]
oh yeah, command-line options I overlook until I need them of course :)
