### ISSUE TITLE
NamedParam and Pair with variables

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#48]
```ruby
var (a, b)
var x = a:b # -> NamedParam
```
it's cool to see how exactly `func(a: b)` is implemented, but especially since `NamedParam` is not really useful outside a function call, maybe `var:var` should only be a NamedParam inside a function call, and be a Pair otherwise? 

Or `var:var` should *always* create a Pair, but inside a function call it has a special `I am a NamedParam, not a Pair value` tag that the invocation understands. (This would need a change in `...`, but I think it would break code that manually unpacks values into named parameters via sugared syntax)

Mostly I just wonder if this is intentional behaviour, it's not so bad to leave the "inconsistency" for `var:var` since `2:3` (usefully) gives `Complex`.

**Comment by trizen** [comment]
> it's cool to see how exactly func(a: b) is implemented

Named params in function and method calls are handled by the Block `_multiple_dispatch()` private function. 
See: https://github.com/trizen/sidef/blob/master/lib/Sidef/Types/Block/Block.pm#L112

> `NamedParam` is not really useful outside a function call

It could be useful in some situations, such as when we want to store the named params in an array:

```ruby
func foo(a, b) { a/b }
var args = [b:7, a:21]
say foo(args...)            #=> 3
```

> var:var should always create a Pair

I agree, but the syntax for named parameters is too useful to change it now. Also the parser can be tricked quite easily in creating a Pair from two variables anyway, as illustrated in the following example:

```ruby
var (a, b) = ("foo", "bar")
say a\:b                   #=> Pair("foo", "bar")
say a.:b                   #=> ==//==
say (a : b)                #=> ==//==
```

**Comment by catb0t** [comment]
Fair, I thought the first one would work if `args...` was a Hash but that was a while ago.

The second part, I didn't expect those to work but I'm glad they do! 

Except, when `a` and `b` are both `nil`, which is a bug, because when `a` or `b` is nil but one is defined, it passes, and `Pair(nil, nil)` is perfectly legal.

**Comment by trizen** [comment]
> Can't call method ":" on undefined..., which is a bug.

It's not really a bug. This is intentional: calling a method on a `nil` value always raises an error. In this case, the method is "`:`".

Keep in mind that "`:`" is not a special syntax for creating a Pair object. It's just a method defined in the String class, which happens to return a Pair object.

See: https://github.com/trizen/sidef/blob/master/lib/Sidef/Types/String/String.pm#L1523

I tend to think that it was probably a bad idea to idea to add it in the first place. :)

For example, this is not defined:
```ruby
/regex/:42
```

even though:

```ruby
Pair(/regex/, 42)
```

is perfectly fine.

**Comment by catb0t** [comment]
That's bizarre, I don't think adding it was bad but I do think implementing it as a method per-object (instead of on Sidef::Object::Object) is bad since it means it's not the same as wrapping the immediates in `Pair()`...
