### ISSUE TITLE
Where to add documentation?

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#50]
The long intro for the question is: 

The GitBooks book is a really good reference for simple language stuff, but leaves out many of the finer details that are covered in the wiki. It's also not editable by anyone else, and I don't think you can make a Sidef organisation for it since https://trizen.gitbooks.io is on "Legacy Gitbooks".

I made a [new Sidef organisation in Gitbook.com, you can join as an administrator](https://www.gitbook.com/invite/sidef?invite=-LQUTtl-CjIvUrtmoo8y) and maybe there is some way to export https://trizen.gitbooks.io/sidef-lang into the new "Spaces" format.

The GitHub wiki has (almost) all the reference on the home page, which I think would make more sense broken into individual pages, but this way you can Ctrl+F and search the entire doc (otherwise you can only search page titles).

GitHub wikis are more convenient but don't have full-text search, meanwhile GitBook is a lot more complicated and not editable by just any user.

[What's new in V2 Gitbook](https://docs.gitbook.com/v2-changes/important-differences)

So should I edit (or re-organise) the GitHub wiki, or wait for the Gitbook route?

**Comment by catb0t** [comment]
Oh, I've just seen there's Github integration for GitBook

https://docs.gitbook.com/integrations/github
https://docs.gitbook.com/integrations/github/content-configuration
https://docs.gitbook.com/integrations/github/limitations
https://docs.gitbook.com/integrations/github/faq

So I imagine you could export the Legacy book to a Github repo, then import it to modern Gitbook, if it's worth it

**Comment by trizen** [comment]
The Sidef book can be edited at: https://github.com/trizen/sidef-book
