### ISSUE TITLE
Slurpy parameters appear to be broken

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#52]
I think the doc is outdated, 

> Alternatively, by using a named variable in the form of `:name`, the arguments are collected inside an hash:

> ```ruby
> func f(:pairs) {
>    say pairs      #=> Hash(a=>1, b=>2)
> }
> f(a => 1, b => 2)
> ```

```ruby
>> f(a => 1, b => 2)                                                            
a
=> true
```
or:
```ruby
>> func a(:k) { k }                                                            
=> func (*k) { #`(a|94509123145096) ... }
>> a(g => 1, r => "ok")                                                          
=> g
>> var x = a(g => 1, r => "ok")                                                    
=> g
>> x.class                                                                      
[AUTOLOAD] Undefined method `g.class' called from main()
=> 
>> x.methods                                                                    
[AUTOLOAD] Undefined method `g.methods' called from main()
=> 
>> x.new                                                                        
[AUTOLOAD] Undefined method `g.new' called from main()
```

The same result when `f` and `a` are declared with `*pairs` or `*k` instead of the `:`.

In both cases, the returned value, obviously not a Hash, appears to be an instantiation of a new object with the name of the first argument as its typename. The other arguments have gone into the aether. Surely this isn't intentional. 

Also, the syntax for calling a `func name(:collect_params) { }` (using hash-style `=>`) is kind of impractical (as `(x => y)` isn't even a concrete object to the user code), and should IMO be consolidated with the NamedParam system, which could be even more useful in this case. 

Imagine if we could write 

```ruby 
func bar(:kw_args) {
  say kw_args
}
bar(a: 1, a_random_arg: "ok", [k: 12, t:14]...)
# -> Hash(a => 1, k => 12 ....
```

Making `:kw_args` into simply a form of `*args` that understands NamedParam would probably also simplify the implementation.

**Comment by trizen** [comment]
Very interesting finding! This happened only when the code was executed in the REPL, due to some in-place changes made by the Perl deparser to the AST.

This has been fixed in the above commit, along with adding support for slurpy global variables:

```ruby
global *a = (1,2,3)
global :b = (a => 1, b => 2)

say a   #=> [1,2,3]
say b   #=> Hash(a => 1, b => 2)
```

Thank you very much for reporting this issue.

---

This code:

```ruby
func bar(:kw_args) {
  say kw_args
}
bar(a: 1, a_random_arg: "ok", [k: 12, t:14]...)
```

is not quite possible, as `NamedParam` objects are processed and unpacked before the function is actually called (in Block `_multiple_dispatch()`).

However, it can very easily be written as:

```ruby
func bar(:kw_args) {
  say kw_args
}
bar(a => 1, a_random_arg => "ok", [k => 12, t => 14]...)
```

outputting:

```ruby
Hash(
    "a" => 1,
    "a_random_arg" => "ok",
    "k" => 12,
    "t" => 14
)
```

**Comment by catb0t** [comment]
Ah, I only ran the code in `-E` and the REPL. Thanks for the fix! 

It took me until now to realise that `=>` is just a combination of the `,` comma operator and the NamedParam `:` operator, and it does something more than a comma inside function calls. 


---

> NamedParam objects are processed and unpacked before the function is actually called

In other words: when using NamedParam, the function's block argument list does not actually receive the names of the NamedParams, whereas it does when using `=>`, is that right?

**Comment by trizen** [comment]
> `=>` is just a combination of the `,` comma operator and the NamedParam `:` operator

That is correct. The fat-comma operator (`=>`) behaves exactly like in Perl 5: it does auto-quoting of an alphanumeric bare-word provided on the left-side of it. Other than, it behaves exactly like the comma operator and can be used interchangeably.

> In other words: when using NamedParam, the function's block argument list does not actually receive the names of the NamedParams, whereas it does when using =>, is that right?

Yes. That is correct.

> what is the specific type of literal created by the (parenthesis-)delimited comma-separated objects in `(x, y, z)`?

`(x, y, z)` is a list of values (same as in Perl). Equivalent with `([x, y, z]...)`

**Comment by catb0t** [comment]
> Lists in Perl are not data structures, they are positions in the source code, determined by the context around them. Lists are basically the transient structures that Perl uses to move data around. You interact with them with all of Perl's syntax, but you can not work with them as a data type.

Pretty much sums up my confusion. Thanks again
