### ISSUE TITLE
included / imported names don't work in Eval or REPL

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#53]
`my_module.sm`: 

```ruby 
module my_module { # removing this declaration  has no effect
  var a = 2
}
```
In the same directory:
```ruby
$ sidef
Sidef 3.50 on linux
Type "help", "copyright" or "license" for more information.
>> include my_module                                                            
=> 2
>> my_module::a                                                                 
Global symbol "$a94599347457488" requires explicit package name (did you forget to declare "my $a94599347457488"?) at (eval 20) line 5.
```

`a` is not in the global scope either, but at least `my_module` appears to correctly be a module-name and not a type-name (ie it cannot be referred to alone).

Also I don't fully understand how to use `import`, but this is from the same `sidef` session as above
```ruby
>> import my_module::a                                                          
=> 
>> a                                                                            
Global symbol "$a94599347457488" requires explicit package name (did you forget to declare "my $a94599347457488"?) at (eval 22) line 5.
=> 
>> my_module::a                                                                 
Global symbol "$a94599347457488" requires explicit package name (did you forget to declare "my $a94599347457488"?) at (eval 26) line 5.
```

equivalent code in a file:
```ruby
include my_module
import my_module::a
say my_module::a+" "+a
```

prints `2 2` from a `script.sf` in the same directory, this is just another weird REPL bug. :D

**Comment by catb0t** [comment]
the `import`` target doesn't have to be a `.sm` module to break in the REPL: 

```ruby
>> module a { var f = 2 }                                                       
=> 2
>> import a::f                                                                  
=> 
>> f                                                                            
Global symbol "$f94125474178840" requires explicit package name
```

**Comment by catb0t** [comment]
Also `include` inside `eval` is ignored (intentional?); if you have `outer_module.sm`: 
```ruby
class A{}
```
`eval-test` (a regular file, containing code)
```ruby 
[
  "This is a Sidef object",
  "which we are going to eval in another program" # these work fine
  a,
  outer_module::A
]
```

and `eval_test.sf`
```ruby
include luciu
import luciu::Test
var a = 1
a                    # to satisfy the warning
say eval(File("eval-test").open_r.slurp)
```

and run `sidef -Wk eval_test.sf`, 
```
File : eval(94081774838136)
Line : 5 : 16
Error: variable <outer_module::A> is not declared in the current scope
```

**Comment by trizen** [comment]
Modules in general seem to not be supported during `eval()`, as illustrated in the following code:

```ruby
say eval("

    module some_module {
        class A {}
    }

    some_module::A()
")    # error: variable <some_module::A> is not declared in the current scope
```

I think the support for modules needs to be redesigned or, at least, re-implemented in a better way, without creating multiple instances of the parser, as this led to this kind of issues.

For now, a file can also be included in a program, using the syntax:

```ruby
include("path/to/file.sf")
```

which does not create an implicit namespace, therefore, if the file contains `class A {}`, it can be accessed simply as `A`.

Thanks for reporting this issues!

**Comment by catb0t** [comment]
Ah, I didn't know about the string argument to `include`, thanks for the workaround. :+1:

**Comment by trizen** [comment]
The `eval()` issue has been fixed in this commit: https://github.com/trizen/sidef/commit/c1eb97edcd0d4be970431fd87694f66b3b6855b4
