### ISSUE TITLE
Del / delete a variable name

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#54]
(Sorry if this already exists, I can't find it)

I think that in Perl there is no such thing as an "undefined name", all names are simply `undef` until you give them a value, or `use strict`.

In Sidef we very obviously have a difference between
```ruby
say x   # compiler error 

var x
say x   # nil
```

for which we are thankful, no more sneaky typos. So in Perl to "delete" a name it's sufficient to make it `undef` as it was before it was defined, but in Sidef a variable name can simultaneously be declared and un-defined.

In Python, which requires you to assign to a name before using it, you can `del x` to get rid of that name, then it is completely removed from the current scope. 

In Python (and Perl) you can also `del(?:ete)? hash[x]` to remove a key and value from a hash, which is technically unnecessary in Sidef since nonexistent keys are `nil` anyway, and you can just set it to `nil` and make it look undefined (until you dump the hash). 

The ability to delete keys from a Sidef hash would be an optimisation for large numbers of keys though.

**Comment by trizen** [comment]
Deleting a variable from the current scope it's an interesting idea. I think it should be possible to add the `del x` or `unvar x` syntax to removing `x` from the current scope (at parse-time). I'll think about it.

Assigning `nil` to a variable it's possible. That would behave exactly like in Perl when `undef` is assigned to a variable. However, the variable itself still exists in the current scope and can be accessed, just that it's not defined (only declared).

Deleting keys from an Hash it's already possible using the `delete` Hash method:

```ruby
var h = Hash(a => 1, b => 2, c => 3)

say h.delete(:a)            #=> 1
say [h.delete(:b, :c)]      #=> [2, 3]

say h                       #=> Hash()
```

**Comment by trizen** [comment]
Got implemented in a somewhat similar way:

```ruby
var a     # declares `a` as variable-type `var`
del a     # re-declares `a` as variable-type `del`
say a     # using a `del` variable, results in a parse-time error
```

**Comment by catb0t** [comment]
Awesome! And the variable can be later re-declared with `var` too, it's a really good implementation
