### ISSUE TITLE
operator / on File / String joins paths 

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#58]
i don't remember the method name but `String/File`and `File/String` should do the platform independent join-paths-by-separator, like https://github.com/lihaoyi/os-lib

**Comment by trizen** [comment]
The operator `/` on strings and dirs for joining paths looks interesting. The current String operator `/` tries to divide the self-string into `n` equal parts (given an integer argument), but I don't think that's very useful (never used it any code), so I think it's pretty safe to change its behavior.

Although, joining paths is already possible, but in a different way:

```ruby
say ::dump File("foo", "bar", "baz")       #=> File("foo/bar/baz")
say ::dump Dir("foo", "bar", "baz")        #=> Dir("foo/bar/baz")

say ::dump Dir("foo")+"bar"                #=> Dir("foo/bar")
say ::dump Dir("foo")+File("bar")          #=> File("foo/bar")
```

**Comment by catb0t** [comment]
I really like how this works:
```ruby
Dir("a")+File("b") + File(".ext") # -> a/b.ext
```
And I can't think of a better way to concatenate literal pathnames than `Dir("a").to_s + "b"`, so no operator for that.

I think being able to also use the `/` in `Dir+File` would be an improvement to readability (not having to assume or test what `+` will do)

I also think `File/File` or `File/String` or `String/File` should convert the LHS to `Dir` and then `+` the operands, so it always adds a separator. 

Because `File.+` is completely different behaviour from `Dir.+`, the option of disambiguating whether we are adding a path separator, when the typenames are missing, is good.
