### ISSUE TITLE
Multiple-assignment should be sequenced in a common scope

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#61]
I haven't looked at Sidef's multiple assignment translation to Perl, but this:
```ruby
var (a, b) = (1, a)
# (1, nil)
```
seems kind of unfortunate. Mainly, because a cool feature of Sidef is ability to reference other arguments inside the same argument list:
```ruby
method option (
    long_name,
    ...    
    doc = long_name.tclc
```
is not in C or Python or any language I know of. 

Sidef must do `var a = 1` in one scope and then a new "scope" for `b` [that has declared but not assigned `a`] which seems contrary to usefulness, and to the above mentioned feature.

I don't suggest that Sidef should dynamically figure out how to sequence the assignments by defined-ness in the mess `var (a, b, c, d) = (d, 1, a, b)`, just that they should be well-defined as left-to-right, declaring and then assigning. -- kind of like operator precedence

So instead of the weird trick that causes `(1, nil)`, I'm suggesting it made equal to 
```ruby
var (a, b)
a = 1; b = a 
```
or 
```ruby
var a; a = 1
var b; b = a
```
and getting `(1, 1)`.

**Comment by trizen** [comment]
Just as in the declaration of parameters, we can do: 

```ruby
var (a=1,b=a)
say [a, b]   #=> [1, 1]
```

**Comment by catb0t** [comment]
I'd never guess such varied syntaxes are possible lol, but thanks of course
