### ISSUE TITLE
Non-alphanumeric function names don't work interactively

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#63]
https://github.com/trizen/sidef/commit/0a3cbbf3d493e0c3e9fe2c841f0f415c5b59e214

this commit doesn't allow `func +(){}` inside the REPL; Deparser.pm was fixed to correctly handle existing Non-ANN callables but Parser.pm still complains 
```
Error: invalid `func` declaration, expected: func (...){...}

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
func +(){}
```
From `Parser.pm:1740` 

```ruby
/\G\h*\{\h*/gc || $self->fatal_error...
```

**Comment by trizen** [comment]
By design, only methods are allowed to have non-alphanumeric names.

**Comment by catb0t** [comment]
Ok, I'll document it :+1:
