### ISSUE TITLE
How to use Text::Table in Sidef?

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#66]
Suppose I wanted to use [Text::Table](https://metacpan.org/pod/Text::Table); I looked at the Sidef wiki on Interacting with Perl Modules, and I roughly translated the example to Sidef:

```ruby
var tt = frequire("Text::Table")

# var tt = %S<Text::Table>

var tb = tt.new(
    "Planet", "Radius\nkm", "Density\ng/cm^3"
)
tb.load(
    [ "Mercury", 2360, 3.7 ],
    [ "Venus", 6110, 5.1 ],
    [ "Earth", 6378, 5.52 ],
    [ "Jupiter", 71030, 1.3 ],
)
print tb
```

If `frequire` is used, the error is `Can't locate object method "_entitle" via package "Planet" at Text/Table.pm line 180` which seems to take `Planet` as a package name. 

If i try to instantiate `tt()` then unsurprisingly, `Undefined subroutine &Text::Table::call`. 

It looks sort of OO in the Perl example (`Text::Table->new`), but if I use `%O` and / or `require`. then `tb` remains a `Sidef::Module::OO=HASH(0x55f7c2978720)` the whole time, or I don't know how to print its data. `tt` is still not callable in that case.

The `var lwp  = require('LWP::UserAgent')...` example in the Wiki works perfectly; does Text::Table need connector Sidef code? 

Please give me the magical incantations :)

**Comment by trizen** [comment]
You're correct, `Text::Table` has an OO interface. The thing missing is the call to the `stringify` method:
```ruby
var tt = require("Text::Table")

var tb = tt.new(
    "Planet", "Radius\nkm", "Density\ng/cm^3"
)
tb.load(
    [ "Mercury", 2360, 3.7 ],
    [ "Venus", 6110, 5.1 ],
    [ "Earth", 6378, 5.52 ],
    [ "Jupiter", 71030, 1.3 ],
)
print tb.stringify
```

Alternatively, as documented in the wiki, an OO module-name can also be accessed as `%O<Module::Name>`, while a subroutine-oriented one as `%S<Module::Name>`.

For this example, it's also possible to write:

```ruby
require("Text::Table")
var tb = %O<Text::Table>.new(...)
```

**Comment by catb0t** [comment]
Perfect, thank you!
