### ISSUE TITLE
why nil function calls and expressions  aren't stringified in the same way? 

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#72]
```
>> ""                                                                           
=> 
>> [].first                                                                     
=> 
>> [][0]                                                                        
=> nil
>> var c                                                                        
=> nil
>> ->{}()                                                                       
=> 
>> ->{return nil}()                                                             
=> nil
>> ->{}() == nil                                                                
=> true
```

Usually I expect the return value `=>   [blank]` to actually mean `=> ""`, but in the case of `[].first` of course this is `nil`, but for some reason it's turned into an empty string when printed by the REPL. You can tell it's `nil`, because `Can't call method "dump" on an undefined value`.

But, it doesn't happen when the source isn't a direct method call, or when the method call `return nil`s explicitly.

**Comment by trizen** [comment]
By default, an empty function returns an empty list, which is not quite equivalent with an explicit `nil`.

This can be illustrated as:

```ruby
say [->{}()]          #=> []
say [->{nil}()]       #=> [nil]
```
