### ISSUE TITLE
Initialisers / constructors like init() aren't usable

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#73]
The first two classes are how I usually circumvent the lack of constructors. TLDR, is it intentional that `new` and `init` are impossible to invoke from Sidef code, so they are Perl-API-only? 

Since `self` isn't bound inside a definition of `new`, then the programmer would have to know the unique internal variable name / refaddr of the class they're trying to construct, and inject `Sidef::Runtime::WithNew9234034...->new(args)` into the parser's execution... so I don't think that's right.

As for `init`, it's invoked automatically, so calling it directly in order to satisfy an error just makes a new error, or the interpreter never even gets to the `.init` call. 

The motivation for a constructor that takes arguments, in addition to the `class name (args) {}`, is that inside the constructor you can assign and process arguments instead of burdening the consuming code with the specifics. 

```ruby
class TakesArgs (_a) {
  -> a { self._a }
}

class WithSetup {
  has _a
  -> setup (new_a) { self._a = new_a }
  -> a { self._a }
}

# class WithNew {
#   has _a
#   -> new (new_a) { self._a = new_a }
#   -> a { self._a }
# }

class WithInit {
  has _a
  -> init (new_a) { self._a = new_a }
  -> a { self._a }
}

class WithInitArgs (_a) {
  -> init (new_a) { self._a = new_a }
  -> a { self._a }
}

var w

# candidate WithInit() does not match WithInit(Number), invoked as WithInit(3)
w = WithInit(3)
say w.dump

# candidate WithInit.init(self, new_a) does not match init(WithInit), invoked as init(WithInit(_a: nil))
w = WithInit()
say w.dump

# candidate WithInitArgs.init(self, new_a) does not match init(WithInitArgs), invoked as init(WithInitArgs(_a: 3))
w = WithInitArgs(3)
say w.dump

# candidate WithInitArgs(_a) does not match WithInitArgs(), invoked as WithInitArgs()
w = WithInitArgs()
say w.dump
```

**Comment by trizen** [comment]
Thanks. I will consider in the future redesigning the classes. 

For now, I guess you can do something like this:

```ruby
class Example() {
    method setup(new_a) {
        __CLASS__.def_method(:a, -> (self) {
            new_a
        })
    }
}

var obj = Example()
obj.setup(42)
say obj.a               #=> 42
```

**Comment by catb0t** [comment]
Hm, you still have to call `setup` in that case,  but it's an interesting idea...

**Comment by trizen** [comment]
Yeah, I know, it's not so pretty.

Alternatively, taking advantage of the `init` method, it's possible to do:

```ruby
class Example(a, b, :extra) {
    method init {
        for k,v in (extra) {
            __CLASS__.def_method(k, -> (self) {
                2*v
            })
        }
    }
}

var obj = Example(1, 2, c => 3, d => 4)

say obj.a               #=> 1
say obj.b               #=> 2
say obj.c               #=> 6
say obj.d               #=> 8
```

**Comment by catb0t** [comment]
oh, that's how init works. brilliant!

**Comment by catb0t** [comment]
`__CLASS__.def_method(name)` overwrites any previous method by that name, what is the method called that adds an overload with the given name and argument list?  Or I have to use `LazyMethod` for that?

**Comment by trizen** [comment]
> what is the method called that adds an overload with the given name and argument list?

This is only possible by doing something like this:

```ruby
class Example(a, b, :extra) {

    method init {
        for k,v in (extra) {

            -> tmp(self) {
                "[#{k}] #{v} without arg"
            }

            -> tmp(self, arg) {
                "[#{k}] #{v} with arg=#{arg}"
            }

            __CLASS__.def_method(k, tmp)
        }
    }
}

var obj = Example(1, 2, c => 3, d => 4)

say obj.a               #=> 1
say obj.b               #=> 2
say obj.c               #=> [c] 3 without arg
say obj.c(42)           #=> [c] 3 with arg=42
say obj.d               #=> [d] 4 without arg
say obj.d(43)           #=> [d] 4 with arg=43
```

**Comment by catb0t** [comment]
This is the kind of metaprogramming and language design that makes me feel alive. :100:
