### ISSUE TITLE
Literal string parser can't find the closing quote on long strings with escapes 

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#75]
```shell
$ python3 -c "print(\"\\\"\" + (\"\\\1\" * 100000) + \"\\\"\")" | sidef
sidef: You made me die. Shame on you!

File : -
Line : 1 : 65535
Error: can't find the quoted string terminator <<">>

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1
^
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Behind all the backslash escapes this prints a very long string of `"\1\1\1\1\1"` (the byte 0x1) to Sidef within string delimiters. It doesn't have to be all escapes, Sidef will also die if a very long string happens to contain `\n` at a very high index, like Base64 for example 

```
sidef: Death before dishonour?

File : eval(94596951896952)
Line : 3 : 2555921
Error: can't find the quoted string terminator <<">>

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
\nARwrw5caAAAAAAABAAAAAAAAAMKUw5caAAAAAABXw5gaAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAA\n
^
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
########
File : .multifactor.db
Line : 3 : 2555921
Error: can't find the quoted string terminator <<">>

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
\nARwrw5caAAAAAAABAAAAAAAAAMKUw5caAAAAAABXw5gaAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAA\n
^
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Unrelated to eval, as it happens with all strings.

Earlier it seemed to only happen at index `65540` / `65535` which I thought was suspiciously close to `2^16` and so maybe this was an inherent limitation of Perl's regex input length, but now it's choking at 2.55 million -- although that is within a percentage of `2^31`...

**Comment by catb0t** [comment]
Long strings work fine on their own of course 

```shell
$ python3 -c "print(\"say eval('\" + (\"0\" * 10000000) + \"')\")" | sidef
0
```

**Comment by trizen** [comment]
This is indeed due to a limitation of the Perl regex engine, which makes it impossible for a string to contain more than `2^15 - 1` escapes.

For example:

```console
% sidef -E 'print ("\"", "a\\nb"*(2**15 - 1), "\"")' | sidef          # works
% sidef -E 'print ("\"", "a\\nb"*(2**15), "\"")' | sidef              # fails
```

However, using double quoted here-documents, the limitation goes away, as here-documents are parsed in a different way:

```console
sidef -E 'print ("<<\"EOT\";\n", "a\\nb"*100000, "\nEOT")' | sidef
```

See also: https://www.effectiveperlprogramming.com/2018/12/perl-v5-30-lets-you-match-more-with-the-general-quantifier/
