### ISSUE TITLE
Const variable sub names in modules sometimes aren't invoked

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#77]
...leading to 

```
Bareword "VALUE94526908439640" not allowed while "strict subs" in use at (eval 5) line 5.
Bareword "VALUE94526908439640" not allowed while "strict subs" in use at (eval 5) line 5.
BEGIN not safe after errors--compilation aborted at (eval 5) line 5.
```

The code is 

```ruby
module F {
  const VALUE = "any value"
}

# works
say "works "+(nil || F::VALUE)

class A {
  method f {
    # works
    say "works "+F::VALUE
    say "fails "+(nil ||F::VALUE)
  }
}


func x {
  say "works "+F::VALUE
  say "fails "+(nil ||F::VALUE)
}

var a = A()
a.f
```
Reproducing this is very tricky because it's very particular as to where it will fail. 

When a "foreign" (non-parent of the current) module's `const` value is referred to by name within a function or class method, then the sub name won't get its needed `()` invoking parentheses, depending on the kind of expression in which it appears, for example a `||`.

If you change `const VALUE`, to `var VALUE` or `define VALUE` it runs fine, so it's with `const` only.

Snipped deparsed output; the bug is marked by `<-- HERE` in 

```perl
    use constant {
        String947984412975281 =>
          Sidef::Types::String::String->new("any\ value"),
        String947984407478881 => Sidef::Types::String::String->new("works\ "),
        String947984405465521 => Sidef::Types::String::String->new("fails\ "),
    };
    my $new94798440647328;
    my $f94798440626944;
    my ($a94798440326208);
    BEGIN { $Sidef::Runtime::OP4394798440286224 = "\+" }

    sub VALUE94798440788424() {
        state $_94798440788424= do { (Sidef::Runtime::String947984412975281) }
    }
    (
        (
            CORE::say(
                ( (Sidef::Runtime::String947984407478881) )
                ->$Sidef::Runtime::OP4394798440286224(
                    (undef) || ( (VALUE94798440788424) )          <-- HERE
                )
            )
        ) ? Sidef::Types::Bool::Bool::TRUE : Sidef::Types::Bool::Bool::FALSE
    );
```

**Comment by catb0t** [comment]
For some reason, I managed to create a method where the bug appears for **any mention** of the name of the `const` value defined in the module. 

In the example above the name `F::VALUE` is okay to say on a line by itself; use it in a `||` and it gets invoked wrong. 

In this method, maybe just for how much code is around it, `Factor::QUIET_PIPE` or `Factor::FACTOR_DIR` on lines by themselves also generate the bug. 

```ruby
        Factor::QUIET_PIPE # becomes a bareword sub name without ()
        self.fbash = shell_words::FactorBash(
          Dir( self.options(){'factor-dir'} || Factor::FACTOR_DIR ), #
          subcommand_output: !( self.options(){'quiet-subcom'} || Factor::QUIET_PIPE )  #
        )
        ...
```

https://github.com/catb0t/multifactor/blob/7e1e31d9cf32c21cc224b47322a400862e637d82/multifactor.sm#L173

**Comment by trizen** [comment]
Interesting issue. Thanks for reporting. Should be fixed in the above commit.
