### ISSUE TITLE
Optimization level 2 breaks / disables inheritance across modules 

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#78]
file inher.sm

```
class Sup {}
var a = 1
```

file inher1.sf
```
include inher
say inher::a
say inher::Sup() # ok
class Der < inher::Sup {}
```

```ruby
$ sidef -kO1 scratch_scripts/inher1.sf 
1
$ sidef -kO2 scratch_scripts/inher1.sf 
sidef: My brain just exploded.

File : scratch_scripts/inher1.sf
Line : 6 : 14
Error: can't find `Sup` class, expected an existent class name

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
class Der() < Sup {};
              ^
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
If you comment out the line inheriting from `Sup` and run with -O2, then `1` is still printed, as we can still access the variable `inher::a`, and we can instantiate the class `Sup()` across modules.

However, the inheritable parent `Sup` is not available with -O2.

**Comment by catb0t** [comment]
By the way, you can still inherit from the class in the same module, but not when it's been included.

**Comment by trizen** [comment]
Thanks for reporting.

**Comment by catb0t** [comment]
This also happens with cross-module included subsets and `-O2`.

**Comment by trizen** [comment]
Thanks. Fixed in the above commit.
