### ISSUE TITLE
Cross-module imports of sub-modules are not possible

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#83]
mod1.sm

```ruby 
module Mod {
  func myfunction {}
}
```
mod2.sf
```ruby
include mod1

# variable is not in scope
mod1::Mod::myfunction()

# variable does not exist
import mod1::Mod
Mod::myfunction()

# variable does not exist
import mod1::Mod::myfunction
myfunction()
```

alternatively, a similar (or the same exact) thing demonstrated in one source file 

```ruby
module Outer {
  module Inner {
    func myfunction {}
  }
}

# no variation of this line works; all give "variable does not exist"
import Outer::Inner::myfunction
```
As far as I have been able to tell, it's not currently possible to access these names without Perl.eval.

**Comment by catb0t** [comment]
Similarly I think this should be possible in this way, but maybe I'm misunderstanding 
```
sidef -E'class X{}; module G { module F { class Y { has x main::X } } } say G::F::Y().dump'
sidef: I'm broken. Fix me, or show this to someone who can fix

File : -E
Line : 1 : 73
Error: variable <G::F::Y> is not declared in the current scope

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lass X{}; module G { module F { class Y { has x main::X } } } say G::F::Y().dump
                                                                        ^
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by trizen** [comment]
Modules do nest, but namespaces do not (maybe they should?).

```ruby
class X { }

module G {
    module F {
        class Y { main::X }
    }
}

say F::Y().dump     #=> Y()

module G::F {
    class Z { main::X }
}

say G::F::Z().dump  #=> Z()
```

**Comment by catb0t** [comment]
I think it would make sense if the module nesting hierarchy was represented by the namespace hierarchy. If flat namespaces are an optimisation, then that's fine too.

But in the `mod1` example above, `mod1::myfunction` is also not available in `mod2.sf`.

**Comment by trizen** [comment]
Currently, the function is available as `Mod::myfunction`, but this may change in the future.

**Comment by catb0t** [comment]
Hmm, well, it's weird but it works. Thanks.

**Comment by catb0t** [comment]
```
module M {
  var x = 1
  enum { y=2, z }
}

say M::x # => 1
say M::y # => not declared 
say M::z # => not declared 
```

Enum members inside modules don't seem to be accessible?

**Comment by trizen** [comment]
Fixed [here](https://github.com/trizen/sidef/commit/58d19f5883c8ca59592573f16822cd9a6783f5e2). Thanks for reporting.

**Comment by catb0t** [comment]
Hmm, some sub-module name resolution has changed to be module-relative when `main` is involved?  This works as you would expect

```ruby
module Mod {

  subset MySub < Str

  class MyClass {}

  module T {
    func t (c < Mod::MySub, Mod::MyClass m) {
      say "#{c} #{m}"
    }
  }
}

func x (Mod::MyClass h, f < Mod::MySub) {
  say "f: #{f} h: #{h}"
}
```
`Mod::MySub` is resolved correctly in all scopes, by the same name.

When `Mod` is in a file alone, call it `sc.sm` 
```ruby
subset MySub < Str

class MyClass {}

module T {
  func t (main::MyClass m, c < main::MySub) {
    say "#{c} #{m}"
  }
}
```
You may not refer to `MySub` or `MyClass` as `sc::MySub` or `sc::MyClass` when running `sidef sc.sm` directly. 

That's fine, but when including `sc.sm` like this: 
```ruby
include sc

func x (f < sc::MySub, sc::MyClass h) {
  say "f: #{f} h: #{h}"
}
```

And running that file, then `main::MySub` etc in `sc.sm` are resolved to the current file's `main` namespace, where there is no `MySub` -- but there is `sc::MySub`. 

```
File : /home/cat/Sync/projects/misc/sidef/subset_scope/sc.sm
Line : 6 : 6
Error: variable <main::MyClass> is not declared in the current scope

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
main::MyClass
```
So to use `sc.sm` as a module you have to change `main::` to `sc::`, but to use it as a script, it needs to say `main::`.

**Comment by trizen** [comment]
The idea of a module stored in an `.sm` file, is that it should not include other modules with it.

So in `sc.sm` there should only be:

```ruby
subset MySub < Str
class MyClass {}
```

and in `sc.sf`, we can have:

```ruby
include sc

module T {
  func t (sc::MyClass m, c < sc::MySub) {
    say "#{c} #{m}"
  }
}

func x (f < sc::MySub, sc::MyClass h) {
  say "f: #{f} h: #{h}"
}
```

Alternatively, since module `T` is dependent on `sc`, we can create `T.sm`:

```ruby
include sc
func t (sc::MyClass m, c < sc::MySub) {
  say "#{c} #{m}"
}
```

and in `sc.sf` we can have:

```ruby
include T

func x (f < sc::MySub, sc::MyClass h) {
  say "f: #{f} h: #{h}"
}
```

**Comment by catb0t** [comment]
Now I'll remember to write more files, fewer `modules` :)
