### ISSUE TITLE
Try/Catch don't treat returned lists / multiple values  properly

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#90]
```ruby
func multi {
  try {
    var f = :try_branch
    # die ;
    (true, :a, :b, f)
  } catch {
      |_, msg|
    say msg
    (false, :a, :b, :catch_branch)
  }
}

{
    |*_|
  say "my arguments are: #{_}"
}( @|multi() )
```

`my arguments are` is either `["try_branch"]` or `["catch_branch"]` depending on whether you uncomment the `die`. in other words, when evaluating the blocks, only their last value is taken, because they are not taken in a list context, but in a last-comma-value context.

**Comment by trizen** [comment]
Good catch :)
