### ISSUE TITLE
Test whether an object is a typename or constructed 

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#93]
3fbdcba481b85b38c245b76dde35cda5cd0d51fb

This is an excellent new feature, and this progress (probably for the better) gets rid of an implementation detail that was the only way to tell the difference between `""` and the `String` class or `1` and the `Number` class or `Object.new` and the `Object` class. 

Specifically, with

```ruby
    func is_typename (Object obj) -> Bool {
      [:compile_to_perl, :code_interactive].all{
          |mth|
        obj.methods.grep{ _ ~~ mth }
      } && obj.refaddr==0
    }
```

the tests used to pass: 

```ruby
class MyClass {}
assert( is_typename(Object) )
assert( is_typename(String) )
assert( is_typename(MyClass) )
assert( ! is_typename(MyClass()) )
assert( ! is_typename(1) )
assert( ! is_typename("") )
assert( ! is_typename(String()) )
```

`T.refaddr` is still 0 for typenames, but that feels flimsy too -- in `is_typename` it was just an extra bit of security to check both conditions.

`Object.~~` uses `! CORE::ref($arg)`, which is true when `$arg` is `String` or `Object` and not `""` or `Object.new`. `Object.ref` in Sidef has never done this though, `X().ref` and `X.ref` are the same.

I'm not making a pull request because I don't know what the right answer is. 

Naively I would propose new `Object.is_constructed` / `.is_typename` methods, but I think these require some `$self{constructed} = 1` thing at the end of every built-in and user-defined package's `new` method, which is not ideal I don't think.

**Comment by trizen** [comment]
There is also the `Object.can(method_name)`, which tests if an object can respond to a given method:

```ruby
func is_typename (Object obj) -> Bool {
  [:say, :print].all{ |mth|
    obj.can(mth)
  } && obj.refaddr==0
}
```

Notice that the `compile_to_perl` and `code_interactive` methods are defined in the Sidef module. Previously the test incorrectly passed due to a bug that was fixed in https://github.com/trizen/sidef/commit/3fbdcba481b85b38c245b76dde35cda5cd0d51fb.

Regarding the newly proposed methods, I think they are helpful and have been implemented in https://github.com/trizen/sidef/commit/5b080938491ebe0cd41ca2e033b35ff9bbe4f313.

**Comment by catb0t** [comment]
Cool. What's the difference between `Object.can` (from `UNIVERSAL::can`?) and `Object.respond_to`, which is declared in `Object.pm`? Since `respond_to` calls `UNIVERSAL::can($self, "$method")` are they the same? 

> test incorrectly passed due to a bug 

:D 

![a](https://imgs.xkcd.com/comics/workflow.png)

**Comment by trizen** [comment]
They are pretty much the same.

The only key difference is that `obj.can()` calls directly the `can` special Perl method, which can be redefined multiple times in a class hierarchy, and returns a raw `CODE` reference on success.

On the other hand, `respond_to` ignores a redefined `can` method and always calls `UNIVERSAL::can` and returns `true` or `false`.

Probably it's better to use `respond_to`.

Funny xkcd. :rofl:
