### ISSUE TITLE
ConstInit is not within the optimising deparser's scope 

### ISSUE THREAD

**Issue by catb0t** [trizen/sidef#94]
```ruby
class X {
  has const   a = :a
  has define  b = :b
  has const   c = /c/
}

say X().a
say X().b
say X().c
```

Using `sidef -kO2 file.sf` gives ``[INFO] `ConstInit` is parsed as a prefix method-call at file.sf line 2``, which is the warning given when something that should be a typename isn't a known name. The resulting Sidef is valid though.

With `sidef -krO0 file.sf` I can see why

```ruby
class main::X(){
    has(ConstInit a)=("a");
    has(ConstInit b)=("b");
    (has(ConstInit c)=(/c/))
};
say(main::X->call()->a());
say(main::X->call()->b());
say(main::X->call()->c());
```
Maybe `ConstInit` is not an existent class name when the optimising deparser is called in `O2`?

**Comment by trizen** [comment]
The correct syntax for declaring a `has` attribute, is:

```ruby
has name = value
```

Everything else works by accident. :)

**Comment by catb0t** [comment]
Yes, I thought so. They do *work* though...
